services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: yamoney
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data