@apiurl = http://localhost:8000

## POST purchase
POST {{apiurl}}/purchase HTTP/1.1
Content-Type: application/json

{
    "location": "shopping 2",
    "price": 50,
    "bank": "Nubank"
}

## List purchase
GET {{apiurl}}/purchase